version: '3.8'

services:
  back:
    container_name: client_back
    build: ./backend
    command: gunicorn server.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    networks:
      - server
    volumes:
      - ./backend:/app
      - /app/env

  front:
    container_name: client_front
    build: ./frontend
    ports:
      - "8081:8081"
    #    depends_on:
    #      - back
    volumes:
      - ./frontend:/app
      - /frontend/node_modules

networks:
  server:
    external: true